# t/ximacrypt_test.pl
#
# Offline unit test for Plugins::Ximalaya::XimaCrypt + Plugins::Ximalaya::Sign.
# Run from anywhere:  perl t\ximacrypt_test.pl
# Requires: JSON::PP, Digest::SHA, Compress::Zlib, MIME::Base64 (all core in
# Strawberry Perl; bundled with LMS).
#
# Directory layout mirrors the LMS user-plugin mechanism: the plugin lives at
# <plugin root>/Ximalaya/*.pm and LMS puts .../InstalledPlugins/Plugins on
# @INC, so the package Plugins::Ximalaya::Sign resolves to
# Plugins/Ximalaya/Sign.pm. Here t/Plugins is a directory junction to
# ../Ximalaya and we chdir to t/, so relative resolution (including Sign.pm's
# device_info.json lookup via __FILE__) matches production behaviour.
#
# Compares against fixtures.json generated by m0/gen_fixtures.py (Python is
# the verified reference implementation from M0).

use strict;
use warnings;
no warnings 'once';    # Slim::...::CAPTURE/RESPONSE live in the stub file
use FindBin;
use File::Spec;

use lib File::Spec->catdir($FindBin::Bin);          # Slim::* stubs + junction
chdir $FindBin::Bin or die "cannot chdir $FindBin::Bin: $!\n";

# main::INFOLOG is always defined inside LMS; tests need the constant too,
# otherwise Sign.pm fails to compile under 'use strict subs'.
use constant INFOLOG => 0;

use JSON::PP qw(decode_json);
use MIME::Base64 qw(encode_base64 decode_base64);
use Compress::Zlib qw(compress uncompress);
use Digest::SHA qw(sha256_hex);
use Encode qw(encode_utf8);

my $fail = 0;
sub check {
	my ($name, $ok, $detail) = @_;
	if ($ok) {
		print "ok   - $name\n";
	}
	else {
		$fail++;
		print "FAIL - $name" . ($detail ? ": $detail" : '') . "\n";
	}
}

# ---------------------------------------------------------------- load fixtures
my $fixtures_path = "$FindBin::Bin/fixtures.json";
open my $fh, '<:raw', $fixtures_path or die "cannot read $fixtures_path: $!\n";
local $/;
my $fx = decode_json(<$fh>);
close $fh;

# ---------------------------------------------------------------- XimaCrypt
require Plugins::Ximalaya::XimaCrypt;

check('XimaCrypt load-time self-test', Plugins::Ximalaya::XimaCrypt->selftest_ok ? 1 : 0);

for my $i (0 .. $#{ $fx->{aes} }) {
	my $v = $fx->{aes}[$i];
	my $ct = Plugins::Ximalaya::XimaCrypt->aes_ecb_encrypt(pack('H*', $v->{key}), pack('H*', $v->{pt}));
	check("aes_ecb_encrypt vector $i", unpack('H*', $ct) eq $v->{ct});

	my $pt = Plugins::Ximalaya::XimaCrypt->aes_ecb_decrypt(pack('H*', $v->{key}), pack('H*', $v->{ct}), 1);
	check("aes_ecb_decrypt vector $i", unpack('H*', $pt) eq $v->{pt});
}

for my $i (0 .. $#{ $fx->{urls} }) {
	my $v = $fx->{urls}[$i];
	my $plain = Plugins::Ximalaya::XimaCrypt->decrypt_url($v->{enc});
	# decrypt_url returns raw UTF-8 bytes; fixtures strings are utf8-flagged
	# (JSON). Decode the bytes (croak on invalid sequences) for comparison.
	my $ok = defined $plain
		&& Encode::decode_utf8($plain, Encode::FB_CROAK() | Encode::LEAVE_SRC()) eq $v->{plain};
	check("decrypt_url sample $i", $ok,
		defined $plain ? "got " . substr($plain, 0, 60) : 'undef');
}

# pass-through of plain/undef input
check('decrypt_url passthrough undef', !defined Plugins::Ximalaya::XimaCrypt->decrypt_url(undef));
check('decrypt_url passthrough plain', Plugins::Ximalaya::XimaCrypt->decrypt_url('https://a.xmcdn.com/x.mp3') eq 'https://a.xmcdn.com/x.mp3');

# ---------------------------------------------------------------- Sign chain
# The Sign module is async (SimpleAsyncHTTP); offline we verify the three
# deterministic stages and then run the full module against a stub transport.
my $s = $fx->{sign};

my $payload = encode_utf8($s->{device_json_with_ts});
check('sign: utf8 bytes == python string_to_uint8', sha256_hex($payload) eq $s->{payload_sha256});

# Different zlib builds may emit different (all valid) deflate streams, so
# compare roundtrip semantics instead of bytes.
my $compressed = compress($payload, 6);
check('sign: zlib level-6 roundtrip', sha256_hex(uncompress($compressed)) eq $s->{payload_sha256});

# --- full Sign.pm through the stub transport (t/Slim/...) -------------------
{
	# the wire response is base64 text (as hdaa returns it)
	$Slim::Networking::SimpleAsyncHTTP::RESPONSE = $s->{hdaa_response_b64};

	my $got_sign;
	my $err;
	require Plugins::Ximalaya::Sign;
	Plugins::Ximalaya::Sign->gen(
		sub { $got_sign = shift },
		sub { $err = shift },
	);

	# server-side view of the captured request body:
	# AES-decrypt -> inflate -> JSON; Sign.pm stamps Zf5 with the live clock,
	# so normalise it before comparing against the fixture payload.
	my $server_view = eval {
		uncompress(
			Plugins::Ximalaya::XimaCrypt->aes_ecb_decrypt(
				'm9ZtRrz:qujT8@da',
				$Slim::Networking::SimpleAsyncHTTP::CAPTURE,
				1
			)
		);
	};
	my ($norm) = map { s/"Zf5":\d+/"Zf5":T/gr } ($server_view // '');
	my ($norm_ref) = map { s/"Zf5":\d+/"Zf5":T/gr } ($s->{device_json_with_ts});
	check('Sign: request body matches python payload', defined $server_view
		&& $norm eq $norm_ref);
	check('Sign: xm-sign assembled', defined $got_sign && $got_sign eq $s->{expected_xm_sign},
		defined $got_sign ? "got '$got_sign'" : (defined $err ? "err '$err'" : 'no callback'));
}

print $fail ? "\n$fail FAILURE(S)\n" : "\nALL TESTS PASSED\n";
exit($fail ? 1 : 0);
